export const tokens = {
  color: {
    surface: 'var(--ew-surface)',
    onSurface: 'var(--ew-on-surface)',
    surfaceMuted: 'var(--ew-surface-muted)',
    primary: 'var(--ew-primary)',
    onPrimary: 'var(--ew-on-primary)',
    border: 'var(--ew-border)',
    muted: 'var(--ew-muted)',
    danger: 'var(--ew-danger)',
    onDanger: 'var(--ew-on-danger)',
    accent: 'var(--ew-accent)',
    neutral: {
      50: 'var(--ew-neutral-50)',
      100: 'var(--ew-neutral-100)',
      200: 'var(--ew-neutral-200)',
      300: 'var(--ew-neutral-300)',
      400: 'var(--ew-neutral-400)',
      500: 'var(--ew-neutral-500)',
      600: 'var(--ew-neutral-600)',
      700: 'var(--ew-neutral-700)',
      800: 'var(--ew-neutral-800)',
      900: 'var(--ew-neutral-900)',
      950: 'var(--ew-neutral-950)',
    },
    primaryRamp: {
      50: 'var(--ew-primary-50)',
      100: 'var(--ew-primary-100)',
      200: 'var(--ew-primary-200)',
      300: 'var(--ew-primary-300)',
      400: 'var(--ew-primary-400)',
      500: 'var(--ew-primary-500)',
      600: 'var(--ew-primary-600)',
      700: 'var(--ew-primary-700)',
      800: 'var(--ew-primary-800)',
      900: 'var(--ew-primary-900)',
      950: 'var(--ew-primary-950)',
    },
  },
  font: {
    sans: 'var(--ew-font-sans)',
    mono: 'var(--ew-font-mono)',
  },
  text: {
    xs: 'var(--ew-text-xs)',
    sm: 'var(--ew-text-sm)',
    base: 'var(--ew-text-base)',
    lg: 'var(--ew-text-lg)',
    xl: 'var(--ew-text-xl)',
    '3xl': 'var(--ew-text-3xl)',
  },
  leading: {
    tight: 'var(--ew-leading-tight)',
    normal: 'var(--ew-leading-normal)',
    loose: 'var(--ew-leading-loose)',
  },
  space: {
    0: 'var(--ew-space-0)',
    1: 'var(--ew-space-1)',
    2: 'var(--ew-space-2)',
    3: 'var(--ew-space-3)',
    4: 'var(--ew-space-4)',
    5: 'var(--ew-space-5)',
    6: 'var(--ew-space-6)',
    7: 'var(--ew-space-7)',
    8: 'var(--ew-space-8)',
    9: 'var(--ew-space-9)',
    10: 'var(--ew-space-10)',
    11: 'var(--ew-space-11)',
    12: 'var(--ew-space-12)',
  },
  radius: {
    none: 'var(--ew-radius-none)',
    sm: 'var(--ew-radius-sm)',
    md: 'var(--ew-radius-md)',
    lg: 'var(--ew-radius-lg)',
    xl: 'var(--ew-radius-xl)',
    full: 'var(--ew-radius-full)',
  },
  shadow: {
    xs: 'var(--ew-shadow-xs)',
    sm: 'var(--ew-shadow-sm)',
    md: 'var(--ew-shadow-md)',
    lg: 'var(--ew-shadow-lg)',
    xl: 'var(--ew-shadow-xl)',
    '2xl': 'var(--ew-shadow-2xl)',
    inner: 'var(--ew-shadow-inner)',
  },
  motion: {
    duration: {
      instant: 'var(--ew-duration-instant)',
      fast: 'var(--ew-duration-fast)',
      normal: 'var(--ew-duration-normal)',
      moderate: 'var(--ew-duration-moderate)',
      slow: 'var(--ew-duration-slow)',
      slower: 'var(--ew-duration-slower)',
    },
    ease: {
      default: 'var(--ew-ease-default)',
      in: 'var(--ew-ease-in)',
      out: 'var(--ew-ease-out)',
      inOut: 'var(--ew-ease-in-out)',
      spring: 'var(--ew-ease-spring)',
    },
  },
  zIndex: {
    hide: 'var(--ew-z-hide)',
    base: 'var(--ew-z-base)',
    raised: 'var(--ew-z-raised)',
    dropdown: 'var(--ew-z-dropdown)',
    sticky: 'var(--ew-z-sticky)',
    overlay: 'var(--ew-z-overlay)',
    modal: 'var(--ew-z-modal)',
    popover: 'var(--ew-z-popover)',
    toast: 'var(--ew-z-toast)',
  },
} as const;

export type Tokens = typeof tokens;
